export {
  OPEN_SLIDE_CANVAS_HEIGHT,
  OPEN_SLIDE_CANVAS_WIDTH,
  OPEN_SLIDE_DENSITIES,
  OPEN_SLIDE_MAX_BLOCKS,
  OPEN_SLIDE_MOTIONS,
  OPEN_SLIDE_NUDGE_PX,
  OPEN_SLIDE_NUDGE_SHIFT_PX,
  OPEN_SLIDE_PADDING,
  OPEN_SLIDE_PAGE_COUNTS,
  OPEN_SLIDE_ROLES,
  addOpenSlideTextBlock,
  duplicateOpenSlideBlock,
  extractJsonObject,
  moveOpenSlideBlock,
  nudgeOpenSlideBlock,
  openSlideDeckSchema,
  parseOpenSlideDeck,
  parseOpenSlideModelText,
  readOpenSlideChoices,
  removeOpenSlideBlock,
  setOpenSlideAccent,
  setOpenSlideBlockText,
  setOpenSlidePageNotes,
  toneColor,
} from "./deck";
export type {
  OpenSlideAlign,
  OpenSlideBlock,
  OpenSlideBrief,
  OpenSlideDeck,
  OpenSlideDensity,
  OpenSlideDesign,
  OpenSlideMotion,
  OpenSlidePage,
  OpenSlidePageCount,
  OpenSlideRole,
  OpenSlideTone,
  OpenSlideWeight,
} from "./deck";
export { draftOpenSlideDeck } from "./draft";
export { OPEN_SLIDE_SYSTEM } from "./harness";
