import * as THREE from "../../node_modules/three/build/three.module.js";
import { buildNultron } from "../../character.js";
import { applyPose } from "../../rig.js";
const [state, prop] = process.argv.slice(2);
const root = buildNultron();
applyPose(root, state);
root.updateMatrixWorld(true);
const o = root.getObjectByName(`nx-prop-${prop}`);
const q = new THREE.Quaternion(); const p = new THREE.Vector3();
o.matrixWorld.decompose(p, q, new THREE.Vector3());
const f = (v) => `[${v.x.toFixed(2)}, ${v.y.toFixed(2)}, ${v.z.toFixed(2)}]`;
const ax = (x, y, z) => new THREE.Vector3(x, y, z).applyQuaternion(q);
console.log("parent", o.parent?.name, "prop origin", f(p), "local X", f(ax(1,0,0)), "Y", f(ax(0,1,0)), "Z", f(ax(0,0,1)));
const g = o.getObjectByName("grip");
console.log("grip found:", g?.name, "parent", g?.parent?.name, "rot", g?.rotation.toArray().slice(0,3).map(v=>v.toFixed(3)).join(","));
const gp = new THREE.Vector3(); g.getWorldPosition(gp); console.log("grip world", f(gp));
const e = new THREE.Euler().setFromQuaternion(o.quaternion);
console.log("prop local rot (deg)", [e.x, e.y, e.z].map((v) => (v * 180 / Math.PI).toFixed(1)).join(", "), "pos", f(o.position));
const par = o.parent; const pq = new THREE.Quaternion(); par.matrixWorld.decompose(new THREE.Vector3(), pq, new THREE.Vector3());
const pax = (x,y,z)=> new THREE.Vector3(x,y,z).applyQuaternion(pq);
console.log("parent world axes X", f(pax(1,0,0)), "Y", f(pax(0,1,0)), "Z", f(pax(0,0,1)));
const pe = new THREE.Euler().setFromQuaternion(par.quaternion);
console.log("parent local rot (deg)", [pe.x, pe.y, pe.z].map((v) => (v * 180 / Math.PI).toFixed(1)).join(", "), "parent local pos", f(par.position));
