import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--color-ink)",
        inkbase: "var(--color-text)",
        paper: "var(--color-paper)",
        app: "var(--color-bg)",
        navy: "var(--color-accent)",
        mist: "var(--color-mist)",
        bg: "var(--bg)",
        surface: "var(--surface)",
        faint: "var(--text-3)",
        line: "var(--line)",
        danger: "var(--danger)",
        ok: "var(--ok)",
        accent: {
          DEFAULT: "var(--accent)",
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          300: "var(--color-accent-300)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          600: "var(--color-accent-600)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          900: "var(--color-accent-900)",
          mid: "var(--accent)",
          soft: "var(--accent-soft)",
          pale: "var(--accent-soft)",
          wash: "var(--accent-soft)",
        },
        divider: "var(--color-divider)",
      },
      fontFamily: {
        heading: ["var(--font-heading)"],
        body: ["var(--font)"],
        sans: ["var(--font)"],
      },
      fontSize: {
        xs: ["13px", { lineHeight: "1.5" }],
        sm: ["16px", { lineHeight: "1.6" }],
        base: ["16px", { lineHeight: "1.6" }],
        lg: ["18px", { lineHeight: "1.45" }],
        xl: ["20px", { lineHeight: "1.4" }],
        "2xl": ["28px", { lineHeight: "1.2" }],
        "3xl": ["24px", { lineHeight: "1.15" }],
        "4xl": ["24px", { lineHeight: "1.1" }],
        "5xl": ["24px", { lineHeight: "1.05" }],
      },
      borderRadius: {
        sm: "8px",
        md: "8px",
        lg: "8px",
        xl: "16px",
        "2xl": "16px",
        "3xl": "16px",
        pill: "999px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        card: "var(--shadow-card)",
        float: "var(--shadow-float)",
      },
    },
  },
  plugins: [],
};

export default config;
