/** Gateway catalog roles from docs/internal/gateway-model-selection.md (2026-09-13). First Section 6 role, not id-keyword heuristics. */
export const GATEWAY_BEST_FOR: Record<string, string> = {
  "gpt-5.2": "Coding",
  "gpt-5.4": "Coding",
  "gpt-5.4-mini": "Coding",
  "gpt-5.4-nano": "Fast drafts",
  "gpt-5.4-pro": "Deep reasoning",
  "gpt-5.5": "Deep reasoning",
  "gpt-5.6-luna": "Fast drafts",
  "gpt-5.6-sol": "Deep reasoning",
  "gpt-5.6-terra": "Everyday chat",
  "gpt-6-astra": "Deep reasoning",
  "gpt-image-2.5-flare": "Image",
  "gpt-image-2.5-sunburst": "Image",
  "doubao-seedream-4-0-250828": "Image",
  "doubao-seedream-4-5-251128": "Image",
  "doubao-seedream-5-0-260128": "Image",
  "doubao-seedream-5-0-pro-260628": "Image",
  "gpt-image-2": "Image",
  "gpt-image-2-count": "Image",
  "grok-imagine-image-quality": "Image",
  "grok-imagine-video": "Video",
  "grok-imagine-video-1.5-preview": "Video",
  "happyhorse-1.0-video-edit": "Video",
  "happyhorse-1.1-i2v": "Video",
  "mj_blend": "Image",
  "mj_custom_zoom": "Image",
  "mj_describe": "Image",
  "mj_edits": "Image",
  "mj_high_variation": "Image",
  "mj_imagine": "Image",
  "mj_inpaint": "Image",
  "mj_low_variation": "Image",
  "mj_modal": "Image",
  "mj_pan": "Image",
  "mj_reroll": "Image",
  "mj_upsample_action": "Image",
  "mj_upscale": "Image",
  "mj_variation": "Image",
  "mj_video": "Image",
  "mj_zoom": "Image",
  "nano-banana": "Image",
  "nano-banana-2": "Image",
  "nano-banana-pro": "Image",
  "omni-fast": "Video",
  "omni-fast-v2v": "Video",
  "suno_lyrics": "Audio",
  "suno_music": "Audio",
  "veo_3_1": "Video",
  "veo_3_1-fast": "Video",
  "gpt-4.1": "Strict format",
  "gpt-4.1-mini": "Fast drafts",
  "gpt-4o": "General chat",
  "gpt-4o-mini": "Fast drafts",
  "gpt-5-mini": "Fast drafts",
  "gpt-5-nano": "Fast drafts",
  "gpt-5.5-pro": "Deep reasoning",
  "claude-haiku-4-5": "Fast drafts",
  "claude-haiku-4-5-20251001": "Fast drafts",
  "claude-opus-4-7": "Coding",
  "claude-opus-4-8": "Coding",
  "claude-opus-5": "Everyday chat",
  "claude-sonnet-5": "Everyday chat",
  "claude-fable-5": "Deep reasoning",
  "claude-opus-4-6": "Coding",
  "claude-sonnet-4-6": "Everyday chat",
  "gemini-2.5-flash": "Fast drafts",
  "gemini-2.5-flash-image": "Image",
  "gemini-2.5-pro": "Long documents",
  "gemini-3-flash": "Everyday chat",
  "gemini-3-pro-image-preview": "Image",
  "gemini-3.1-flash-image-preview": "Image",
  "gemini-3.1-flash-lite": "Fast drafts",
  "gemini-3.1-flash-lite-image": "Image",
  "gemini-3.1-pro": "Deep reasoning",
  "gemini-3.1-pro-preview": "Deep reasoning",
  "gemini-3.5-flash": "Everyday chat",
  "gemini-embedding-001": "Embedding",
  "gemini-embedding-2-preview": "Embedding",
  "gemini-2.5-flash-lite": "Fast drafts",
  "deepseek-v4-flash": "Fast drafts",
  "deepseek-v4-pro": "Deep reasoning",
  "glm-5.2": "Coding",
  "glm-5.2-fast-preview": "Fast drafts",
  "gui-plus": "Coding",
  "kimi-k2.6": "Everyday chat",
  "kimi-k2.7-code": "Coding",
  "minimax-m2.5": "Fast drafts",
  "minimax-m2.7": "Fast drafts",
  "minimax-m3": "Everyday chat",
  "qwen-audio-3.0-realtime-flash": "Audio",
  "qwen-audio-3.0-realtime-plus": "Audio",
  "qwen-flash": "Fast drafts",
  "qwen-flash-character": "Fast drafts",
  "qwen-image-2.0": "Image",
  "qwen-image-2.0-pro": "Image",
  "qwen-mt-flash": "Translation",
  "qwen-mt-lite": "Translation",
  "qwen-mt-plus": "Translation",
  "qwen3-coder-flash": "Coding",
  "qwen3-livetranslate-flash": "Translation",
  "qwen3-max": "General chat",
  "qwen3-omni-flash-2025-12-01": "Audio",
  "qwen3-omni-flash-realtime": "Audio",
  "qwen3-tts-instruct-flash-realtime": "Audio",
  "qwen3-vl-embedding": "Embedding",
  "qwen3-vl-rerank": "Rerank",
  "qwen3.5-122b-a10b": "Strict format",
  "qwen3.5-27b": "Coding",
  "qwen3.5-35b-a3b": "Fast drafts",
  "qwen3.5-397b-a17b": "Coding",
  "qwen3.5-flash": "Fast drafts",
  "qwen3.5-livetranslate-flash-realtime": "Translation",
  "qwen3.5-ocr": "Fast drafts",
  "qwen3.5-omni-flash": "Audio",
  "qwen3.5-omni-flash-realtime": "Audio",
  "qwen3.5-omni-plus": "Audio",
  "qwen3.5-omni-plus-realtime": "Audio",
  "qwen3.5-plus": "Long documents",
  "qwen3.6-27b": "Coding",
  "qwen3.6-35b-a3b": "Coding",
  "qwen3.6-flash": "Fast drafts",
  "qwen3.6-max-preview": "Coding",
  "qwen3.6-plus": "Coding",
  "qwen3.7-flash": "Fast drafts",
  "qwen3.7-max": "Deep reasoning",
  "qwen3.7-plus": "Everyday chat",
  "qwen3.7-text-embedding": "Embedding",
  "qwen3.8-max": "Deep reasoning",
  "text-embedding-v4": "Embedding",
  "wan2.7-image": "Image",
  "wan2.7-image-pro": "Image",
  "z-image-turbo": "Image",
  "qwen-image-edit": "Image",
  "qwen-mt-turbo": "Translation",
  "doubao-seed-2-0-code-preview-260215": "Coding",
  "doubao-seed-2-0-lite-260428": "Everyday chat",
  "doubao-seed-2-0-mini-260428": "Fast drafts",
  "doubao-seed-2-0-pro-260215": "Deep reasoning",
  "doubao-seed-2-1-pro-260628": "Deep reasoning",
  "doubao-seed-2-1-turbo-260628": "Everyday chat",
  "doubao-seedance-2-0-260128": "Video",
  "doubao-seedance-2-0-fast-260128": "Video",
  "doubao-seedance-2-0-mini-260615": "Video",
  "dreamina-seedance-2-0-260128": "Video",
  "dreamina-seedance-2-0-ep": "Video",
  "dreamina-seedance-2-0-fast-260128": "Video",
  "dreamina-seedance-2-0-fast-ep": "Video",
  "mimo-v2.5-asr": "Audio",
  "seed-1.6": "Fast drafts",
  "seed-1.6-flash": "Fast drafts",
  "seed-1.8": "Fast drafts",
  "seed-2.0-lite": "Everyday chat",
  "seed-2.0-mini": "Fast drafts",
  "seed-2.0-pro": "Deep reasoning",
  "seedance-1.0-pro": "Video",
  "seedance-1.0-pro-fast": "Video",
  "seedance-1.5-pro": "Video",
  "seedance-2.0": "Video",
  "seedance-2.0-fast": "Video",
  "seedance-2.0-mini": "Video",
  "seedance-2.5": "Video",
  "seedream-4.0": "Image",
  "seedream-4.5": "Image",
  "seedream-5.0-pro": "Image",
  "kimi-k3": "Deep reasoning",
  "claude-fable-5-1": "Deep reasoning",
  "claude-opus-4-5-20251101": "Coding",
  "gpt-5.3-codex": "Coding",
  "glm-5.3": "Coding",
  "glm-5.3-flash": "Everyday chat",
  "gpt-oss-120b": "Fast drafts",
};

export const EVERYDAY_MODEL_IDS: ReadonlySet<string> = new Set([
  "gpt-5.6-terra",
  "claude-sonnet-5",
  "gemini-3.5-flash",
  "qwen3.7-plus",
  "minimax-m3",
  "doubao-seed-2-1-turbo-260628",
  "gpt-5.6-luna",
  "glm-5.3-flash",
]);

