// Regenerates dims.json from layout.js + the built model (plain node, no GPU).  node gen-dims.mjs
import { writeFileSync } from "node:fs";
import * as THREE from "three";
import { buildNultron } from "./character.js";
import { L, CAMERAS } from "./layout.js";
import { GRIPS_R, GRIP_AXIS } from "./hands.js";
import { torsoR, torsoFrontZ } from "./body.js";
import { superFrontZ } from "./geo.js";
import { helmetParams } from "./head.js";

const root = buildNultron();
root.updateMatrixWorld(true);
const r3 = (v) => [+v.x.toFixed(4), +v.y.toFixed(4), +v.z.toFixed(4)];
const wp = (name) => r3(root.getObjectByName(name).getWorldPosition(new THREE.Vector3()));
const pivotNames = ["nx-root", "nx-body", "nx-neck", "nx-head", "nx-antenna", "nx-antenna-tip", "nx-gem", "nx-gem-glow", "nx-ear-l", "nx-ear-r"];
for (const s of ["l", "r"]) pivotNames.push(`nx-shoulder-${s}`, `nx-elbow-${s}`, `nx-hand-${s}`, `nx-grip-${s}`, `nx-hip-${s}`, `nx-leg-${s}`, `nx-foot-${s}`);
const pivots = Object.fromEntries(pivotNames.map((n) => [n, wp(n)]));

const bounds = (name) => {
  const b = new THREE.Box3().setFromObject(root.getObjectByName(name));
  return { min: r3(b.min), max: r3(b.max) };
};
const all = new THREE.Box3().setFromObject(root);
const noAntenna = (() => {
  // bounds of everything except the antenna, to state the "2.0 units tall" claim honestly
  const ant = root.getObjectByName("nx-antenna");
  const antBox = new THREE.Box3().setFromObject(ant);
  const glow = root.getObjectByName("nx-gem-glow");
  const parent = ant.parent;
  parent.remove(ant);
  parent.remove(glow);
  const b = new THREE.Box3().setFromObject(root);
  parent.add(ant);
  parent.add(glow);
  return { body: { min: r3(b.min), max: r3(b.max) }, antenna: { min: r3(antBox.min), max: r3(antBox.max) } };
})();

const H = L.head;
const P = helmetParams(false);
const mitt = L.mitt;
const dims = {
  _about: "Generated by gen-dims.mjs from layout.js and the built model. Do not hand-edit; change layout.js and regenerate.",
  units: "1 unit = half the height to the top of the helmet; Y up; character faces +Z; origin on the ground between the feet.",
  handedness: "Left/right are SCREEN-relative: nodes ending in -l are at x < 0 (viewer's left), -r at x > 0.",
  restPose: "All pivot rotations are 0: arms hang straight down (-Y), legs straight, head level and facing +Z. Visible by default: eyes-open, mouth-idle, hand fist. Shoulders/elbows/hips/neck/wrist rotate about their own origin.",
  bounds: {
    all: { min: r3(all.min), max: r3(all.max) },
    bodyNoAntenna: noAntenna.body,
    antenna: noAntenna.antenna,
    helmetTopY: +(H.center[1] + H.ry).toFixed(3),
    width: +(all.max.x - all.min.x).toFixed(3),
  },
  pivotsWorld: pivots,
  head: {
    center: H.center,
    radius: H.rx,
    radii: { x: H.rx, y: H.ry, z: H.rz },
    note: `helmet is a superquadric egg; head-local origin = helmet centre; nx-head sits at this centre, nx-neck (the pivot) is at y=${L.neckY}`,
    frontZAt: (_x, _y) => undefined,
  },
  faceplate: {
    windowLocal: { cx: L.window.cx, cy: L.window.cy, halfW: L.window.a, halfH: L.window.b, exponent: L.window.n },
    visibleHalfSize: [+(L.window.a - 0.03).toFixed(3), +(L.window.b - 0.03).toFixed(3)],
    plateFrontZAtCentre: +(superFrontZ(0, L.window.cy, P) - L.window.inset).toFixed(4),
    note: "coordinates are head-local (relative to nx-head)",
  },
  eyes: { centresLocal: [[-L.eye.x, L.eye.y], [L.eye.x, L.eye.y]], radii: [L.eye.rx, L.eye.ry], note: "head-local, on the plate" },
  mouthCentreLocal: [L.mouth.x, L.mouth.y],
  gem: { centreWorld: wp("nx-gem"), radius: L.gem.r },
  antenna: { baseWorld: wp("nx-antenna"), tipWorld: wp("nx-antenna-tip"), ballRadius: L.antenna.ball },
  earPod: {
    l: { centreWorld: wp("nx-ear-l"), radius: L.ear.r, halfDepth: 0.095, outward: [-1, 0, 0] },
    r: { centreWorld: wp("nx-ear-r"), radius: L.ear.r, halfDepth: 0.095, outward: [1, 0, 0] },
    note: "a disc facing sideways: headphone cups should be about radius 0.17, centred on the pod centre, offset outward by ~0.05",
  },
  torso: {
    centreY: 0.72,
    yRange: [L.torso.yBottom, L.torso.yTop],
    radiusAt: { y0_5: +torsoR(0.5).toFixed(3), y0_7: +torsoR(0.7).toFixed(3), y0_9: +torsoR(0.9).toFixed(3) },
    frontZAt: { x0_y0_735: +torsoFrontZ(0, 0.735).toFixed(4) },
    splitY: L.torso.splitY,
  },
  badge: { centreWorld: [0, L.badge.y, +(torsoFrontZ(0, L.badge.y) + 0.017).toFixed(4)], radius: L.badge.r },
  mittRadius: mitt,
  hand: {
    frame: "hand-local axes = world axes at rest (NOT mirrored per side): origin = wrist, the arm continues down -Y, +Z = character front, palm faces the body (+X for -l hands, -X for -r hands).",
    variants: ["open", "point", "thumb", "hold", "fist"],
    gripPoints: {
      r: Object.fromEntries(Object.entries(GRIPS_R).map(([k, v]) => [k, v])),
      l: Object.fromEntries(Object.entries(GRIPS_R).map(([k, v]) => [k, [-v[0], v[1], v[2]]])),
    },
    gripAxis: GRIP_AXIS,
    gripNote: "nx-grip-<side> is an empty child of nx-hand-<side>; character.js setHand(root, side, variant) toggles the variant and moves it to that variant's grip. For 'hold' the object runs along hand-local Z (front to back) through the curled fingers.",
    wristToPalmCentre: 0.078,
  },
  arm: { shoulderToElbow: L.arm.upper, elbowToWrist: L.arm.fore, radii: { upper: L.arm.rUpper, fore: L.arm.rFore }, shoulderBallRadius: L.shoulder.r },
  leg: { hipBallRadius: L.hip.r, boot: { centreX: L.boot.x, halfSize: [L.boot.rx, L.boot.ry, L.boot.rz], centreZ: L.boot.cz }, soleY: 0 },
  camera: CAMERAS,
  meshBounds: { helmet: bounds("nx-helmet"), faceplate: bounds("nx-faceplate"), torso: bounds("nx-torso") },
};
delete dims.head.frontZAt;
writeFileSync(new URL("./dims.json", import.meta.url), `${JSON.stringify(dims, null, 2)}\n`);
console.log("dims.json written", Object.keys(dims).length, "keys; bounds", JSON.stringify(dims.bounds.all));
