// Nultron 3D rig: applyPose(root, state, { t, mode, props }).
//
// Owner: poser. Data lives in ./poses.json (the source of truth; this file only interprets it).
//
// WHAT IT DOES
//   Sets the rotation of every pivot in the contract's scene graph, shows exactly one variant of the eyes, mouth and each
//   hand, attaches the state's prop(s) and fx, and evaluates the state's clip or loop when a time is given.
//   Every call rewrites ALL of that from scratch, so applying pose B after pose A gives the same scene as applying B on a
//   fresh model (tests: poses/test/rig.test.mjs).
//
// REST POSE
//   The first call snapshots the model's rest transforms (position + quaternion of every pivot, and of nx-body) into
//   root.userData.nxRig.rest. Pose angles are DELTAS from that snapshot, so the model may bake a rest tilt into a pivot.
//   Nothing else may move the pivots between calls.
//
// ANGLE CONVENTIONS (degrees; every triple is [a, b, c]; left/right are SCREEN-relative, -l is at -X)
//   The same numbers on -l and -r give a mirror-symmetric pose.
//   neck, antenna, body.lean   [nod, turn, tilt]
//                                nod  + = pitch forward (face looks down, antenna tip leans toward +Z)
//                                turn + = face turns toward the viewer's right (+X)
//                                tilt + = top leans clockwise as the viewer sees it (toward +X)
//   shoulder-l/r               [elev, azim, twist]  (the arm hangs along -Y at rest)
//                                elev  = angle between the upper arm and straight down (0 hanging, 90 horizontal, 180 up)
//                                azim  = direction of that swing around the vertical: 0 = straight out sideways,
//                                        90 = straight forward (+Z), -90 = backward
//                                twist = roll about the upper arm; + turns the elbow's bend direction toward the body's
//                                        midline (the bend direction is the arm's local +Z: forward when the arm hangs)
//   elbow-l/r, hand-l/r        [flex, inward, roll]
//                                flex   + = forearm (hand) folds toward the arm's local +Z (forward when hanging)
//                                inward + = swings toward the body's midline
//                                roll   + = roll about the limb axis, toward the midline
//   hip-l/r                    [swing, out, twist]
//                                swing + = leg swings forward (+Z); out + = leg swings away from the midline
//   body.offset                [x, y, z] in units, added to nx-body's rest position
//   Legs stay under the body when it leans: the rig counter-rotates the hips by the lean.
//
// STATE SHAPE (poses.json, "states"): { note, pivots: { neck, antenna, shoulder-l/r, elbow-l/r, hand-l/r, hip-l/r: [a,b,c] },
//   body: { offset, lean }, eyes, mouth, handL, handR, prop: [ {name, attach, pos, rot, scale?, hide?, at?, pop?} ],
//   fx: [ {name, pos, rot?, scale?, at?, pop?} ], clip?, loop? }. poses.json is generated by poses/build-poses.mjs.
//
// CLIPS AND LOOPS (poses.json)
//   state.clip = { fps: 12, frames: [ { f, pivots?, body?, eyes?, mouth?, handL?, handR?, ease? }, ... ] }
//     frames are sparse keyframes at frame numbers f (12 fps; also pscale = prop scale multiplier). A channel a keyframe does not list holds the state's
//     still value. After the last keyframe the pose is the still pose exactly, so a one-shot ends on the still frame.
//     ease (on the keyframe a segment ARRIVES at): linear | in | out | inout | back. Variants (eyes, mouth, hands) step.
//   state.loop = { fps, frames: [...] }  same keyframe shape, cyclic: period = frames.length / fps, interpolation wraps.
//   applyPose(root, state, { t }) with t in seconds evaluates the clip (default) or the loop (mode: "loop", or when the
//   state has no clip). Without t the pose is the still one.
//
// PROPS
//   state.prop = { name, attach, pos?, rot?, scale? } or an array of them. attach is
//     "grip-l" | "grip-r"   child of nx-grip-l/r; the prop's own child object named "grip" is put on the grip point
//     "head"                child of nx-head
//     "body"                child of nx-body (follows bob and lean)
//     "root" | "fx"         child of nx-root / nx-fx
//   pos [x,y,z] is in the parent's frame (units), rot [x,y,z] degrees Euler XYZ (about the grip for hand-held props),
//   hide [names] hides those companion children of the prop ("tablet", "picture", "board", ...) so the same piece can
//   be placed on its own; scale a number or [sx,sy,sz] (a negative component mirrors the prop). Hand-held props are placed by their `grip` empty,
//   everything else by its `anchor` empty. at / pop: hidden before clip frame `at`, popping in with an overshoot.
//   Props come from props.js PROPS[name]() (fx too: thinking, surprised, sparks, celebrating, lets-go, wave, sleep); the rig
//   itself builds "tear" and "heart-mini"; an unknown name shows a labelled box.
//   state.fx = [ { name, pos, rot?, scale?, at?, pop? } ]  child of nx-fx, positions in nx-root's frame.

import * as THREE from "three";
import POSES from "./poses.json" with { type: "json" };

let PROPS = {};
try {
  const mod = await import("./props.js");
  PROPS = mod.PROPS ?? {};
} catch {
  // props.js is optional: placeholders stand in.
}

const DEG = Math.PI / 180;
const AX = { x: new THREE.Vector3(1, 0, 0), y: new THREE.Vector3(0, 1, 0), z: new THREE.Vector3(0, 0, 1) };

export const PIVOT_NAMES = [
  "neck",
  "antenna",
  "shoulder-l",
  "shoulder-r",
  "elbow-l",
  "elbow-r",
  "hand-l",
  "hand-r",
  "hip-l",
  "hip-r",
];
export const STATE_NAMES = Object.keys(POSES.states);
export const EYES = ["open", "blink", "happy", "surprised", "closed"];
// Optional eye variants: used when the model has the node, otherwise the rig shows the fallback instead.
export const OPTIONAL_EYES = { wink: "happy" };
export const MOUTHS = ["idle", "talk", "smile", "sad", "o", "sleep"];
export const HANDS = ["open", "point", "thumb", "hold", "fist"];
export const ATTACH = ["grip-l", "grip-r", "head", "body", "root", "fx"];

/** Replace the props table (for callers that cannot rely on the optional ./props.js import). */
export function setProps(table) {
  PROPS = table ?? {};
}

// ---------------------------------------------------------------------------------------------------------------------
// Angle maths (exported: the poses/tools helpers use the same functions the rig does)
// ---------------------------------------------------------------------------------------------------------------------

const qAxis = (axis, deg) => new THREE.Quaternion().setFromAxisAngle(AX[axis], deg * DEG);
const mirrorQ = (q) => new THREE.Quaternion(q.x, -q.y, -q.z, q.w);

export function headQuat([nod = 0, turn = 0, tilt = 0]) {
  return qAxis("y", turn).multiply(qAxis("x", nod)).multiply(qAxis("z", -tilt));
}

/** Right-side quaternion for a shoulder; the left side is its mirror. */
export function shoulderQuat(side, [elev = 0, azim = 0, twist = 0]) {
  const q = qAxis("y", -azim).multiply(qAxis("z", elev)).multiply(qAxis("y", -twist));
  return side === "l" ? mirrorQ(q) : q;
}

/** Elbow and wrist. */
export function flexQuat(side, [flex = 0, inward = 0, roll = 0]) {
  const q = qAxis("x", -flex).multiply(qAxis("z", -inward)).multiply(qAxis("y", -roll));
  return side === "l" ? mirrorQ(q) : q;
}

export function hipQuat(side, [swing = 0, out = 0, twist = 0]) {
  const q = qAxis("x", -swing).multiply(qAxis("z", out)).multiply(qAxis("y", twist));
  return side === "l" ? mirrorQ(q) : q;
}

function pivotQuat(name, v) {
  const side = name.endsWith("-l") ? "l" : name.endsWith("-r") ? "r" : "";
  if (name === "neck" || name === "antenna") return headQuat(v);
  if (name.startsWith("shoulder")) return shoulderQuat(side, v);
  if (name.startsWith("elbow") || name.startsWith("hand")) return flexQuat(side, v);
  if (name.startsWith("hip")) return hipQuat(side, v);
  throw new Error(`nultron rig: unknown pivot "${name}"`);
}

// ---------------------------------------------------------------------------------------------------------------------
// Pose evaluation (still, clip, loop)
// ---------------------------------------------------------------------------------------------------------------------

const ZERO3 = Object.freeze([0, 0, 0]);
const EASES = {
  linear: (u) => u,
  in: (u) => u * u,
  out: (u) => 1 - (1 - u) * (1 - u),
  inout: (u) => (u < 0.5 ? 2 * u * u : 1 - 2 * (1 - u) * (1 - u)),
  back: (u) => {
    const c1 = 1.70158;
    const c3 = c1 + 1;
    return 1 + c3 * (u - 1) ** 3 + c1 * (u - 1) ** 2;
  },
};

const lerp3 = (a, b, u) => [a[0] + (b[0] - a[0]) * u, a[1] + (b[1] - a[1]) * u, a[2] + (b[2] - a[2]) * u];

function stillOf(def) {
  return {
    pivots: Object.fromEntries(PIVOT_NAMES.map((n) => [n, def.pivots?.[n] ?? ZERO3])),
    offset: def.body?.offset ?? ZERO3,
    lean: def.body?.lean ?? ZERO3,
    eyes: def.eyes ?? "open",
    mouth: def.mouth ?? "idle",
    handL: def.handL ?? "fist",
    handR: def.handR ?? "fist",
    pscale: 1,
  };
}

/** The still pose merged with one keyframe's sparse overrides. */
function withKey(still, key) {
  return {
    pivots: Object.fromEntries(PIVOT_NAMES.map((n) => [n, key.pivots?.[n] ?? still.pivots[n]])),
    offset: key.body?.offset ?? still.offset,
    lean: key.body?.lean ?? still.lean,
    eyes: key.eyes ?? still.eyes,
    mouth: key.mouth ?? still.mouth,
    handL: key.handL ?? still.handL,
    handR: key.handR ?? still.handR,
    pscale: key.pscale ?? still.pscale,
  };
}

function blend(a, b, u, stepFrom) {
  const s = stepFrom ?? a;
  return {
    pivots: Object.fromEntries(PIVOT_NAMES.map((n) => [n, lerp3(a.pivots[n], b.pivots[n], u)])),
    offset: lerp3(a.offset, b.offset, u),
    lean: lerp3(a.lean, b.lean, u),
    pscale: a.pscale + (b.pscale - a.pscale) * u,
    eyes: s.eyes,
    mouth: s.mouth,
    handL: s.handL,
    handR: s.handR,
  };
}

/** Seconds a state's clip or loop lasts (0 when it has none). */
export function poseDuration(state, mode = "clip") {
  const def = POSES.states[state];
  const track = mode === "loop" ? def?.loop : def?.clip;
  if (!track) return 0;
  if (mode === "loop") return track.frames.length / (track.fps ?? 12);
  const last = track.frames[track.frames.length - 1];
  return last.f / (track.fps ?? 12);
}

export function hasClip(state) {
  return Boolean(POSES.states[state]?.clip);
}
export function hasLoop(state) {
  return Boolean(POSES.states[state]?.loop);
}

/** The evaluated pose (plain data) of a state at time t. Exported for tests and tools. */
export function evaluatePose(state, opts = {}) {
  const def = POSES.states[state];
  if (!def) throw new Error(`nultron rig: unknown state "${state}"`);
  const still = stillOf(def);
  const { t } = opts;
  if (t === undefined || t === null) return { ...still, fxFrame: Number.POSITIVE_INFINITY };
  const mode = opts.mode ?? (def.clip ? "clip" : def.loop ? "loop" : "still");
  if (mode === "clip" && def.clip) {
    const fps = def.clip.fps ?? 12;
    const fp = Math.max(0, t) * fps;
    const keys = def.clip.frames;
    const last = keys[keys.length - 1];
    if (fp >= last.f) return { ...still, fxFrame: fp };
    if (fp <= keys[0].f) return { ...withKey(still, keys[0]), fxFrame: fp };
    let i = 0;
    while (i < keys.length - 2 && keys[i + 1].f <= fp) i++;
    const k0 = keys[i];
    const k1 = keys[i + 1];
    const u = (fp - k0.f) / (k1.f - k0.f);
    const eased = (EASES[k1.ease ?? "inout"] ?? EASES.inout)(u);
    const a = withKey(still, k0);
    const b = withKey(still, k1);
    return { ...blend(a, b, eased, u >= 1 ? b : a), fxFrame: fp };
  }
  if (mode === "loop" && def.loop) {
    const fps = def.loop.fps ?? 12;
    const keys = def.loop.frames;
    const n = keys.length;
    const fp = ((Math.max(0, t) * fps) % n + n) % n;
    const i = Math.floor(fp);
    const k0 = keys[i];
    const k1 = keys[(i + 1) % n];
    const u = fp - i;
    const eased = (EASES[k1.ease ?? "inout"] ?? EASES.inout)(u);
    return { ...blend(withKey(still, k0), withKey(still, k1), eased, withKey(still, k0)), fxFrame: Number.POSITIVE_INFINITY };
  }
  return { ...still, fxFrame: Number.POSITIVE_INFINITY };
}

// ---------------------------------------------------------------------------------------------------------------------
// Scene binding
// ---------------------------------------------------------------------------------------------------------------------

const warned = new Set();
function warnOnce(msg) {
  if (warned.has(msg)) return;
  warned.add(msg);
  // eslint-disable-next-line no-console
  console.warn(`nultron rig: ${msg}`);
}

function bind(root) {
  if (root.userData.nxRig) return root.userData.nxRig;
  const get = (name) => root.getObjectByName(`nx-${name}`) ?? null;
  const pivots = {};
  const missing = [];
  for (const n of PIVOT_NAMES) {
    const o = get(n);
    if (o) pivots[n] = o;
    else missing.push(`nx-${n}`);
  }
  const body = get("body");
  if (!body) missing.push("nx-body");
  const rest = {};
  for (const [n, o] of Object.entries(pivots)) rest[n] = { p: o.position.clone(), q: o.quaternion.clone() };
  if (body) rest.body = { p: body.position.clone(), q: body.quaternion.clone() };
  const variants = {
    eyes: Object.fromEntries([...EYES, ...Object.keys(OPTIONAL_EYES)].map((v) => [v, get(`eyes-${v}`)])),
    mouth: Object.fromEntries(MOUTHS.map((v) => [v, get(`mouth-${v}`)])),
    handL: Object.fromEntries(HANDS.map((v) => [v, get(`hand-l-${v}`)])),
    handR: Object.fromEntries(HANDS.map((v) => [v, get(`hand-r-${v}`)])),
  };
  for (const [group, table] of Object.entries(variants)) {
    for (const [v, o] of Object.entries(table)) if (!o && !(group === "eyes" && v in OPTIONAL_EYES)) missing.push(`variant ${group}:${v}`);
  }
  const rig = {
    pivots,
    body,
    rest,
    variants,
    fxRoot: get("fx"),
    anchors: { "grip-l": get("grip-l"), "grip-r": get("grip-r"), head: get("head"), body, root, fx: get("fx") },
    cache: new Map(),
    attached: [],
    missing,
  };
  if (missing.length) warnOnce(`model lacks ${missing.join(", ")}`);
  root.userData.nxRig = rig;
  return rig;
}

function setVariant(table, group, want) {
  if (want && !(want in table)) warnOnce(`unknown ${group} variant "${want}"`);
  for (const [name, obj] of Object.entries(table)) if (obj) obj.visible = name === want;
}

/** Shows one hand variant and, like character.js setHand(), moves nx-grip-<side> to that variant's grip point. */
function setHandVariant(rig, side, want) {
  setVariant(rig.variants[side === "l" ? "handL" : "handR"], `hand-${side}`, want);
  const hand = rig.pivots[`hand-${side}`];
  const grip = hand?.getObjectByName(`nx-grip-${side}`);
  const g = hand?.userData?.grips?.[want];
  if (grip && g) grip.position.set(g[0], g[1], g[2]);
}

// ---------------------------------------------------------------------------------------------------------------------
// Fallbacks: two small fx the props builder does not own (tear, heart-mini), and a labelled box for anything unknown
// ---------------------------------------------------------------------------------------------------------------------

function labelTexture(text) {
  if (typeof document === "undefined") return null;
  const c = document.createElement("canvas");
  c.width = 256;
  c.height = 128;
  const g = c.getContext("2d");
  g.fillStyle = "#ffd28a";
  g.fillRect(0, 0, 256, 128);
  g.strokeStyle = "#5a3a00";
  g.lineWidth = 6;
  g.strokeRect(3, 3, 250, 122);
  g.fillStyle = "#5a3a00";
  g.font = "bold 44px sans-serif";
  g.textAlign = "center";
  g.textBaseline = "middle";
  g.fillText(text, 128, 64);
  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}

function gripEmpty(g, x = 0, y = 0, z = 0, name = "grip") {
  const o = new THREE.Object3D();
  o.name = name;
  o.position.set(x, y, z);
  g.add(o);
}

/** A glossy teardrop, tip up, anchor at its centre. */
function buildTear() {
  const pts = [];
  const N = 16;
  for (let i = 0; i <= N; i++) {
    const t = i / N; // 0 bottom .. 1 tip
    const y = -0.07 + t * 0.19;
    const r = t < 0.55 ? 0.055 * Math.sqrt(1 - ((0.55 - t) / 0.55) ** 2) : 0.055 * (1 - (t - 0.55) / 0.45) ** 1.4;
    pts.push(new THREE.Vector2(Math.max(0.0005, r), y));
  }
  const geo = new THREE.LatheGeometry(pts, 28);
  const mat = new THREE.MeshPhysicalMaterial({ color: 0x8fd8f5, roughness: 0.12, clearcoat: 1, clearcoatRoughness: 0.05 });
  const g = new THREE.Group();
  g.name = "nx-prop-tear";
  g.add(new THREE.Mesh(geo, mat));
  gripEmpty(g, 0, 0, 0, "anchor");
  return g;
}

/** A small glossy pink heart, anchor at its centre. */
function buildHeartMini() {
  const s = new THREE.Shape();
  s.moveTo(0, -0.08);
  s.bezierCurveTo(-0.02, -0.06, -0.09, -0.02, -0.09, 0.03);
  s.bezierCurveTo(-0.09, 0.08, -0.04, 0.1, 0, 0.06);
  s.bezierCurveTo(0.04, 0.1, 0.09, 0.08, 0.09, 0.03);
  s.bezierCurveTo(0.09, -0.02, 0.02, -0.06, 0, -0.08);
  const geo = new THREE.ExtrudeGeometry(s, { depth: 0.04, bevelEnabled: true, bevelThickness: 0.02, bevelSize: 0.015, bevelSegments: 4, curveSegments: 20 });
  geo.translate(0, 0, -0.02);
  const mat = new THREE.MeshPhysicalMaterial({ color: 0xf4a3a3, roughness: 0.3, clearcoat: 0.8, clearcoatRoughness: 0.15 });
  const g = new THREE.Group();
  g.name = "nx-prop-heart-mini";
  g.add(new THREE.Mesh(geo, mat));
  gripEmpty(g, 0, 0, 0, "anchor");
  return g;
}

const BUILTIN = { tear: buildTear, "heart-mini": buildHeartMini };

function unknownPlaceholder(name) {
  const g = new THREE.Group();
  g.name = `nx-prop-${name}`;
  g.userData.placeholder = true;
  const tex = labelTexture(name);
  const box = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.2, 0.05), new THREE.MeshStandardMaterial({ color: tex ? 0xffffff : 0xffd28a, map: tex }));
  g.add(box);
  gripEmpty(g);
  gripEmpty(g, 0, 0, 0, "anchor");
  return g;
}

function resolveProp(rig, name) {
  if (rig.cache.has(name)) return rig.cache.get(name);
  let obj = null;
  const factory = PROPS[name] ?? BUILTIN[name];
  if (typeof factory === "function") {
    try {
      obj = factory();
    } catch (err) {
      warnOnce(`prop "${name}" threw while building: ${err.message}`);
    }
  } else warnOnce(`no prop named "${name}" (placeholder shown)`);
  if (!obj) obj = unknownPlaceholder(name);
  rig.cache.set(name, obj);
  return obj;
}

const _m = new THREE.Matrix4();
const _q = new THREE.Quaternion();
const _e = new THREE.Euler();
const _s = new THREE.Vector3();
const _p = new THREE.Vector3();

/** Matrix of `node` relative to `obj` (walks up the parents; independent of anything above obj). */
function relativeMatrix(obj, node) {
  const m = new THREE.Matrix4();
  for (let n = node; n && n !== obj; n = n.parent) {
    n.updateMatrix();
    m.premultiply(n.matrix);
  }
  return m;
}

/**
 * The matrix that places `obj` in its parent frame: T(pos) * R(rot XYZ deg) * S(scale) * inverse(marker), where marker is
 * the prop's own `grip` (hand-held, alignGrip) or `anchor` empty (everything else) so that point lands on pos.
 * Exported so poses/build-poses.mjs can compute where a two-handed prop's grips end up.
 */
export function placementMatrix(obj, spec, alignGrip) {
  const pos = spec.pos ?? ZERO3;
  const rot = spec.rot ?? ZERO3;
  const sc = spec.scale ?? 1;
  const sv = Array.isArray(sc) ? sc : [sc, sc, sc];
  _e.set(rot[0] * DEG, rot[1] * DEG, rot[2] * DEG, "XYZ");
  _q.setFromEuler(_e);
  const m = new THREE.Matrix4().compose(new THREE.Vector3(pos[0], pos[1], pos[2]), _q.clone(), new THREE.Vector3(sv[0], sv[1], sv[2]));
  const marker = obj.getObjectByName(alignGrip ? "grip" : "anchor");
  if (marker) m.multiply(relativeMatrix(obj, marker).invert());
  return m;
}

function place(obj, spec, alignGrip) {
  placementMatrix(obj, spec, alignGrip).decompose(obj.position, obj.quaternion, obj.scale);
}

function detachAll(rig) {
  for (const o of rig.attached) o.removeFromParent();
  rig.attached = [];
}

function attach(rig, obj, parent, spec, alignGrip) {
  if (!parent) {
    warnOnce(`no parent for ${obj.name}`);
    return;
  }
  parent.add(obj);
  obj.visible = true;
  place(obj, spec, alignGrip);
  rig.attached.push(obj);
}

/** Shows every companion child of a prop's `body` (the floating tablet, picture, board...) except those named in `hide`. */
function setCompanions(obj, hide) {
  const body = obj.getObjectByName("body");
  if (!body) return;
  for (const c of body.children) c.visible = !(hide ?? []).includes(c.name);
}

/** Clip-time appearance of a prop or fx: hidden before spec.at (frame), popping in with an overshoot when spec.pop. */
function popIn(obj, spec, pose, extraScale) {
  let k = extraScale;
  if (spec.at !== undefined && Number.isFinite(pose.fxFrame)) {
    const local = pose.fxFrame - spec.at;
    if (local < 0) obj.visible = false;
    else if (spec.pop) k *= EASES.back(Math.min(1, local / 4));
  }
  if (k !== 1) obj.scale.multiplyScalar(Math.max(k, 0.001));
}

// ---------------------------------------------------------------------------------------------------------------------
// applyPose
// ---------------------------------------------------------------------------------------------------------------------

const isPropTable = (o) => {
  const vals = Object.values(o);
  return vals.length > 0 && vals.every((v) => typeof v === "function");
};

/** What a state offers beyond its still pose. */
export function poseInfo(state) {
  const def = POSES.states[state];
  if (!def) throw new Error(`nultron rig: unknown state "${state}"`);
  return {
    note: def.note ?? "",
    hasClip: Boolean(def.clip),
    clipSeconds: poseDuration(state, "clip"),
    hasLoop: Boolean(def.loop),
    loopFps: def.loop?.fps ?? 0,
    loopSeconds: poseDuration(state, "loop"),
    props: [].concat(def.prop ?? []).map((p) => p.name),
    fx: (def.fx ?? []).map((f) => f.name),
  };
}

/**
 * Puts `root` (the nx-root group from buildNultron) into `state`.
 * @param {THREE.Object3D} root
 * @param {string} state one of STATE_NAMES
 * @param {{ t?: number, mode?: "clip" | "loop" | "still", props?: Record<string, () => THREE.Object3D> } | Record<string, () => THREE.Object3D>} [options]
 *   an options object, or (as scene-main.js does) the PROPS table itself
 * @returns {{ state: string, t: number | undefined }}
 */
export function applyPose(root, state, options) {
  let opts = options ?? {};
  // scene-main.js passes the PROPS table itself as the third argument: accept that as well as an options object.
  if (isPropTable(opts)) {
    setProps(opts);
    opts = {};
  }
  if (opts.props) setProps(opts.props);
  const def = POSES.states[state];
  if (!def) throw new Error(`nultron rig: unknown state "${state}"`);
  const rig = bind(root);
  const pose = evaluatePose(state, opts);

  // Body: rest position + offset, rest rotation * lean; hips undo the lean so the legs stay plumb.
  const leanQ = headQuat(pose.lean);
  if (rig.body) {
    rig.body.position.copy(rig.rest.body.p).add(_p.set(pose.offset[0], pose.offset[1], pose.offset[2]));
    rig.body.quaternion.copy(rig.rest.body.q).multiply(leanQ);
  }
  const leanInv = leanQ.clone().invert();

  for (const n of PIVOT_NAMES) {
    const o = rig.pivots[n];
    if (!o) continue;
    o.position.copy(rig.rest[n].p);
    const delta = pivotQuat(n, pose.pivots[n]);
    if (n.startsWith("hip")) delta.premultiply(leanInv);
    o.quaternion.copy(rig.rest[n].q).multiply(delta);
  }

  const eyes = rig.variants.eyes[pose.eyes] || !(pose.eyes in OPTIONAL_EYES) ? pose.eyes : OPTIONAL_EYES[pose.eyes];
  setVariant(rig.variants.eyes, "eyes", eyes);
  setVariant(rig.variants.mouth, "mouth", pose.mouth);
  setHandVariant(rig, "l", pose.handL);
  setHandVariant(rig, "r", pose.handR);

  // Props and fx: detach everything the previous call attached, then attach this state's.
  detachAll(rig);
  const props = def.prop ? (Array.isArray(def.prop) ? def.prop : [def.prop]) : [];
  for (const spec of props) {
    if (!ATTACH.includes(spec.attach)) {
      warnOnce(`state "${state}": bad attach "${spec.attach}"`);
      continue;
    }
    const obj = resolveProp(rig, spec.name);
    attach(rig, obj, rig.anchors[spec.attach], spec, spec.attach.startsWith("grip"));
    setCompanions(obj, spec.hide);
    popIn(obj, spec, pose, pose.pscale);
  }
  const fxList = def.fx ?? [];
  for (const spec of fxList) {
    const obj = resolveProp(rig, spec.name);
    // Two entries with the same fx name need their own instance.
    const inst = rig.attached.includes(obj) ? obj.clone(true) : obj;
    attach(rig, inst, rig.fxRoot ?? root, spec, false);
    popIn(inst, spec, pose, 1);
  }

  root.updateMatrixWorld(true);
  return { state, t: opts.t };
}

export { POSES };
